spring:
  freemarker:
    checkTemplateLocation: false
  main:
    web-environment: false
  datasource:
    url: jdbc:postgresql://localhost:5432/az2416
    username: az2416
    password: 06RGofdF6l
  jpa:
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL9Dialect
      hibernate.batch_size: 100
      ordered_inserts: true
      ordered_updates: true
rest:
  url: http://ethpool.org/api

extraction.interval: 2000 # data exraction schedule in MILLISECONDS


logging:
  path: /var/log
  file: ethpool.log
  level:
    root: INFO
    org.springframwork.web: ERROR
    org.hibernate: ERROR
